### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by softloud** [softloud/metasim#29]
There are multiple points at which the simulation may fail. But I'm not very good at figuring out how to handle this. I'm using [advanced r](http://adv-r.had.co.nz/Exceptions-Debugging.html), but I suspect @rensa's [`collateral::`](https://cran.r-project.org/web/packages/collateral/index.html) package might be better, as there's so much `purrr::`. 

The `metafor::rma` function doesn't always converge. Also need to make sure I'm not generating negative numbers. It's scary and overwhelming and I feel like I'm out of my CS depth. 

Thought @adamhsparks, @kylehamilton, @mpadge might be interested in taking a look, if you have time. 

I've hacked the `metasims` function with a forloop for now, and ideally I'd like to `rap::rap` it or something a bit tidier, but it will do for now. The main thing is to get the whole simulation pipeline running and catch the errors. 

Ideally, I'd like to replace the REML's with fixed-effects models, too, when they fail to converge. 

Welcome to my personal eternal hell. Any thoughts, advice, contributions, most welcome.

**Comment by softloud** [comment]
:thinking: I suspect it will be useful to store the specific error messages using @rensa's package.

**Comment by softloud** [comment]
I should experiment with safely a little bit more. 

Also, from R Packages,

- `log(-1)` produces a warning
- `1 / "a"` produces an error

**Comment by rensa** [comment]
On thing on my post-thesis submission checklist is implementing the proposal in https://github.com/rensa/collateral/issues/8, which is to map both `safely()` _and_ `quietly()` for cases where you aren't sure whether you're gonna hit a warning or an error (which happens a lot in modelling).

Part of that is also creating class-aware extractors for the various side effects—for safely and quietly it's pretty predictable (something like `map(my_safe_col, 'result')`), but it gets trickier if you implement this because it could be either `map(my_safe_col, 'result')` or `map(my_safe_col, c('result', 'result'))` depending on whether you're using `safely()` or `peacefully()` (the proposed combo).

**Comment by softloud** [comment]
Getting there with this. Testing is helping me whittle it down to a sampling problem for particular distributions.

**Comment by softloud** [comment]
Today's plan: troubleshoot -  column ` measure` is unknown. 

Maths was completely borked before. Fixed now, after meeting with KSM this week. I'm very curious to see how much of the issues I was having were because the maths was wrong. Fiddly, too, so really hard for anyone to pick, including me. Maths is fixed y'all! 

Crossing fingers.

**Comment by softloud** [comment]
Okay, so there are entire simulations that I'm not collecting the results for. So, something is going wrong. But it's not consistent. So, that's interesting.

```
> test_df <- function(df) {
+   df %>% 
+     mutate(rows = map(results, nrow)) %>% 
+     filter(rows != "30")
+ }

> list(test_1, test_2, test_3) %>% 
+   map(test_df)
[[1]]
# A tibble: 2 x 11
      k between_study_variation median_ratio  prop rdist parameters n                  id     true_median results rows  
  <dbl>                   <dbl>        <dbl> <dbl> <chr> <list>     <list>             <chr>        <dbl> <list>  <list>
1    50                     0.4          1     0.3 exp   <list [1]> <tibble [100 × 3]> sim_18       0.347 <NULL>  <NULL>
2    50                     0            1.2   0.3 norm  <list [2]> <tibble [100 × 3]> sim_23      67     <NULL>  <NULL>

[[2]]
# A tibble: 6 x 11
      k between_study_variation median_ratio  prop rdist parameters n                  id     true_median results rows  
  <dbl>                   <dbl>        <dbl> <dbl> <chr> <list>     <list>             <chr>        <dbl> <list>  <list>
1    50                     0.2          1     0.3 norm  <list [2]> <tibble [100 × 3]> sim_11      67     <NULL>  <NULL>
2    50                     0.4          1     0.3 norm  <list [2]> <tibble [100 × 3]> sim_17      67     <NULL>  <NULL>
3    50                     0.4          1     0.3 exp   <list [1]> <tibble [100 × 3]> sim_18       0.347 <NULL>  <NULL>
4    50                     0            1.2   0.3 norm  <list [2]> <tibble [100 × 3]> sim_23      67     <NULL>  <NULL>
5    50                     0            1.2   0.3 exp   <list [1]> <tibble [100 × 3]> sim_24       0.347 <NULL>  <NULL>
6    50                     0.4          1.2   0.3 norm  <list [2]> <tibble [100 × 3]> sim_35      67     <NULL>  <NULL>

[[3]]
# A tibble: 7 x 11
      k between_study_variation median_ratio  prop rdist parameters n                  id     true_median results rows  
  <dbl>                   <dbl>        <dbl> <dbl> <chr> <list>     <list>             <chr>        <dbl> <list>  <list>
1     7                     0            1     0.3 exp   <list [1]> <tibble [14 × 3]>  sim_4        0.347 <NULL>  <NULL>
2    50                     0.4          1     0.3 norm  <list [2]> <tibble [100 × 3]> sim_17      67     <NULL>  <NULL>
3    50                     0            1.2   0.3 norm  <list [2]> <tibble [100 × 3]> sim_23      67     <NULL>  <NULL>
4    50                     0            1.2   0.3 exp   <list [1]> <tibble [100 × 3]> sim_24       0.347 <NULL>  <NULL>
5    50                     0.2          1.2   0.3 norm  <list [2]> <tibble [100 × 3]> sim_29      67     <NULL>  <NULL>
6     3                     0.4          1.2   0.3 norm  <list [2]> <tibble [6 × 3]>   sim_31      67     <NULL>  <NULL>
```

**Comment by softloud** [comment]
Getting an error from parameter sets in sampling function for the occasional trial. 

```
> test <- purrr::rerun(10000, metatrial())
 Show Traceback
 
 Rerun with Debug
 Error in rnorm(n, mean = par_1 * exp(beta * this_study_error), sd = par[[2]]) : 
  invalid arguments 
```

**Comment by adamhsparks** [comment]
Sorry, I've been so covered up in my own work lately I've not even had a chance to peak at this.

**Comment by softloud** [comment]
No worries, @adamhsparks, it feels like the project that never ends. Good lord.

**Comment by adamhsparks** [comment]
So I have plenty of time then. Good.
