### ISSUE TITLE
softloud packages missing from Imports

### ISSUE THREAD

**Issue by adam-gruer** [softloud/metasim#49]
Hi Charles,
I couldn't ignore your screenshot on twitter with all the failing Travis builds.
I had a look to see if i could help.
R Cmd Check was failing with this error: 

https://travis-ci.org/adam-gruer/metasim/jobs/508193461#L2745

To me that is a super confusing error.  My interpretation is that metasim is not 'requiring' those packages as in they are not in the Imports section of the Description file.  Any sane, normal person would read that error and not think that is what it means.  There is a little extra required for these two packages as they live on github and not cran.  usethis as a function use_dev_package() that takes care of this for us.  I'll crate a pull request with the change. The Travis build still fails but the failure has been kicked down the road to some tests that are failing.

**Comment by softloud** [comment]
## tasks

- convert adam's tips to tasks 
- convert to zzz.R file, like in dance::
