### ISSUE TITLE
fix bindfactors warning when running `metasims`

### ISSUE THREAD

**Issue by softloud** [softloud/metasim#59]
This is annoying as this keeps making the results of any tests unreadable. 

## tasks 
- [ ] get tests to run

## starting error

```
25: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
```

**Comment by ekothe** [comment]
Do you want to stop it from happening or just suppress the warning?

**Comment by ekothe** [comment]
Do you want to stop it from happening or just suppress the warning?

**Comment by softloud** [comment]
Suppress!
